Web/Controllers/ReservacionController.cs
using ApplicationCore.Services;
using Infraestructure.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using Web.Permisos;
using Web.Utils;

namespace Web.Controllers
{
    public class ReservacionController : Controller
    {
        private readonly IServiceReservacion _Service;

        public ReservacionController() => _Service = new ServiceReservacion();

        // GET: Reservacion
        [CustomAuthorize((int)Roles.Admin)]
        public ActionResult IndexAdmin(int? estado)
        {
            try
            {

                IEnumerable<Reservacion> lista = null;
                if (estado != null)
                {
                    lista = _Service.GetByEstado((int)estado);
                }
                else
                {
                    lista = _Service.GetAll();
                }

                ViewBag.EstadoReservacion = listaEstadoReservacion();

                return View(lista);
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;

                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }


        }
        [CustomAuthorize((int)Roles.Residente)]
        public ActionResult IndexUsuario()
        {
            try
            {

                Usuario usuario = (Usuario)Session["Usuario"];
                ViewBag.listaAreas = listaAreas();
                ViewBag.listaReservacion = _Service.GetAllByIdUsuario(usuario.Id);
                return View();
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;

                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Reservacion oReservacion)
        {
            try
            {
                Usuario usuario = (Usuario)Session["Usuario"];
                oReservacion.FK_Usuario = usuario.Id;
                oReservacion.FK_Estado = 1;
                if (ModelState.IsValid)
                {
                    if (_Service.Save(oReservacion) > 0)
                    {
                        ViewBag.listaReservacion = _Service.GetAllByIdUsuario(usuario.Id);
                        TempData["creada"] = true;
                        return RedirectToAction("IndexUsuario");
                    }

                }
                else
                {
                    ViewBag.listaAreas = listaAreas();
                    ViewBag.listaReservacion = _Service.GetAllByIdUsuario(usuario.Id);
                    return View("IndexUsuario",oReservacion);

                }
                return RedirectToAction("Index");          
  
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;

                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }


        }

        private SelectList listaEstadoReservacion(int? idEstado = 0)
        {

            IServiceEstados<EstadoReservacion> _Service = new ServiceEstadoReservacion();
            IEnumerable<EstadoReservacion> lista = _Service.GetAll();
            return new SelectList(lista, "Id", "Nombre", idEstado);
        }
        [HttpGet]
        public JsonResult ValidarHorario(DateTime fechaEntrada, DateTime fechaSalida, int idAreaComunal)
        {
            try
            {
                bool existeHorario = _Service.ValidarHorario(fechaEntrada, fechaSalida,idAreaComunal);
                return Json(new { existeHorario = existeHorario }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        public SelectList listaAreas(int? id = 0)
        {
            IServiceAreaComunal _Service = new ServiceAreaComunal();
            IEnumerable<AreaComunal> lista = _Service.GetAll();
            return new SelectList(lista, "Id", "Nombre", id);

        }

        public ActionResult GetHorarioById(int id)
        {
            IServiceAreaComunal _Service = new ServiceAreaComunal();
            AreaComunal oArea = null;
            try
            {
                oArea = _Service.GetAreaComunalById(id);
                return Json(new {horaApertura = oArea.HoraApertura.Value.ToString(), horaCierre = oArea.HoraCierre.Value.ToString()}, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;

                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }

        [HttpPost]
        public ActionResult CambiarEstado(int id, string nota, int idEstado = 4 ) //Si no viene, cancelada por usuario
        {
            try
            {
                Usuario usuario = (Usuario)Session["Usuario"];
                IServiceNotificacionUsuario _ServiceNotificaion = new ServiceNotificacionUsuario();
                IEnumerable<Reservacion> lista = null;
                _Service.CambiarEstado(id, nota,idEstado);
                if(usuario.FK_Rol == 1)
                {
                    _ServiceNotificaion.SaveNotificacionUsuario(new NotificacionUsuario { IdNotificacion = 4, IdUsuario = _Service.GetByIdReservacion(id).FK_Usuario, Leida=false });

                    lista = _Service.GetAll();
                    
                }
                else
                {
                    lista = _Service.GetAllByIdUsuario(usuario.Id);
                }
                 return PartialView("~/Views/Shared/Reservacion/_Reservacion.cshtml", lista);

            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;

                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }
    }
}

Web/Views/Reservacion/IndexAdmin.cshtml
@model IEnumerable<Infraestructure.Models.Reservacion>


@using (Html.BeginForm("IndexAdmin", "Reservacion", FormMethod.Get))
{
    <div class="form-group">
        <label class="col-form-label">Estado</label>
        @Html.DropDownList("estado",
                 (SelectList)ViewBag.EstadoReservacion,
                 "Seleccione un estado",
                 htmlAttributes: new { @class = "form-control text-center", @id = "active-filter" })
    </div>

}

<div class="data-tables datatable-dark table-responsive" id="listaReservacion">
    <table id="dataTableReservacion" class="text-center">
        <thead class="text-capitalize">
            <tr>
                <th scope="col">@Html.DisplayNameFor(model => model.Usuario.Nombre)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.FechaEntrada)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.FechaSalida)</th>
                <th scope="col"> @Html.DisplayNameFor(model => model.AreaComunal.Nombre)</th>
                <th scope="col"> @Html.DisplayNameFor(model => model.EstadoReservacion.Nombre)</th>
                <th scope="col">@Html.DisplayNameFor(model => model.Nota)</th>
                <th scope="col">Acción</th>


            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {

                <tr class="selected-row">
                    <td>@item.Usuario.Nombre</td>
                    <td>@item.FechaEntrada</td>
                    <td> @item.FechaSalida</td>
                    <td> @item.AreaComunal.Nombre</td>
                    <td> @item.EstadoReservacion.Nombre</td>
                    <td>
                        @if (item.FK_Estado != 1)
                        {
                            @item.Nota

                        }
                    </td>
                    <td>
                        @if (item.FK_Estado == 1)
                        {
                            <button data-id="@item.Id" title="Cambiar Estado" class="btn bg-warning btn-sm px-3 btnCambiarEstado">
                                <i class="ti-settings text-white"></i>
                            </button>

                        }
                    </td>

                </tr>
            }
        </tbody>
    </table>
</div>

@section scripts {


    <script type="text/javascript">

        const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.addEventListener('mouseenter', Swal.stopTimer)
                toast.addEventListener('mouseleave', Swal.resumeTimer)
            }
        })

        //se ejecuta al seleccionar en el combo de estados
        $(function () {
            $('#active-filter').change(function () {
                $('form').submit();
            });
        });

        $(document).ready(function () {
            $('#dataTableReservacion').DataTable({
                responsive: true,
                "language": {
                    "url": "https://cdn.datatables.net/plug-ins/1.10.25/i18n/Spanish.json"
                },
                "lengthChange": false,
                "paging": false,

            });
        });

        //Se ejecuta al presionar botón de cambiar estado
        $(document).on("click", ".btnCambiarEstado", function () {
            var id = $(this).data('id');

            Swal.fire({
                title: 'Cambiar estado',
                html: '<select id="cmbEstado" class="custom-select">' +
                    '<option value="0" selected>Seleccione una opción de confirmación</option>' +
                    ' <option value="2" >Aceptar</option>' +
                    ' <option value="3">Rechazar</option>' +
                    '</select >' +
                    '<span class="text-warning" id="errorSA"></span>' +
                    '<input id="txtNota" name="txtNota" autocapitalize="off" class="form-control mt-4" placeholder="Nota(opcional)" type="text">',

                showCancelButton: true,
                confirmButtonText: 'Guardar',
                confirmButtonColor: '#5eb548',
                cancelButtonText: 'Cancelar'
            }).then((result) => {
                // Guardar el estado en el servidor usando una solicitud AJAX
                if (result.isConfirmed) {
                    var estado  = $("#cmbEstado").val();
                    var nota = $("#txtNota").val();
                    if (estado == "0") {
                        Toast.fire({
                            icon: 'error',
                            title: 'Debe seleccionar un estado'
                        })
                        return;
                    }
                  
                    $.ajax({
                        url: '/Reservacion/CambiarEstado',
                        type: 'POST',
                        data: {
                            id: id,
                            idEstado : estado,
                            nota: nota,
                        },
                        success: function (response) {

                            Toast.fire({
                                icon: 'success',
                                title: 'La reservación se modificó exitosamente'
                            });

                            $('#listaReservacion').html('');
                            $('#listaReservacion').html(response);

                            $('#dataTableReservacion').DataTable({
                                responsive: true,
                                "language": {
                                    "url": "https://cdn.datatables.net/plug-ins/1.10.25/i18n/Spanish.json"
                                },
                                "lengthChange": false,
                                "paging": false,

                            });
                        },
                        error: function () {
                            Toast.fire({
                                icon: 'error',
                                title: 'Error al cambiar el estado'
                            })
                        }
                    });
                }
            });
        });


    </script>


}