Web/Controllers/AutentificacionController.cs
using ApplicationCore.Services;
using Infraestructure.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Reflection;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.Services.Description;
using Web.Utils;

namespace Web.Controllers
{
    public class AutentificacionController : Controller
    {
        private readonly IServiceAutentificacion _ServiceAutentificacion;
        private readonly IServiceNotificacionUsuario _ServiceNotificacion;

        public AutentificacionController() {
            _ServiceAutentificacion = new ServiceAutentificacion();
            _ServiceNotificacion = new ServiceNotificacionUsuario();
        }


        // GET: Autentificacion
        public ActionResult Login() => View();

        public ActionResult RecuperarContrasenna() => View();

        [HttpPost]
        public  ActionResult RestablecerContrasenna(string email) {
            try
            {


                if (_ServiceAutentificacion.RestablecerContrasennaByEmail(email) > 0)
                {
                    Session["correo"] = email;
                    return Json(true, JsonRequestBehavior.AllowGet);
                }
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos!" + ex.Message;
                return RedirectToAction("Default", "Error");
            }
         
           

        }

        [HttpPost]
        public  ActionResult VerificarCodRestablecer(string codigo)
        {
            String email = "";
            try
            {
                email = (string)Session["correo"];
                bool resultado = _ServiceAutentificacion.verificarCodRestablecer(email,codigo);
                return Json(resultado, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos!" + ex.Message;
                return RedirectToAction("Default", "Error");
            }



        }

        [HttpPost]
        public ActionResult CambiarClave(string clave)
        {
            String email = "";
            try
            {
                email = (string)Session["correo"];
                if (_ServiceAutentificacion.CambiarClave(email, clave) > 0) {
                    return Json(true, JsonRequestBehavior.AllowGet);
                }
                return Json(false, JsonRequestBehavior.AllowGet);

            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos!" + ex.Message;
                return RedirectToAction("Default", "Error");
            }



        }


        [HttpPost]
        public ActionResult Login(Usuario oUsuario)
        {

            try
            {


                ModelState.Remove("Nombre");
                ModelState.Remove("Apellido1");
                ModelState.Remove("Apellido2");
                ModelState.Remove("Cedula");
                ModelState.Remove("FK_Rol");
                ModelState.Remove("Activo");
                if (ModelState.IsValid)
                {
                    oUsuario = _ServiceAutentificacion.Login(oUsuario.Email, oUsuario.Clave);

                    if (oUsuario != null)
                    {
                        if ((bool)!oUsuario.Activo)
                        {
                            ViewData["Mensaje"] = "El usuario se encuentra inactivo";
                            return View();
                        }
                        IEnumerable<NotificacionUsuario> listaNotificaciones = _ServiceNotificacion.GetNotificacionByIdUser(oUsuario.Id);
                        if (listaNotificaciones != null)
                        {
                            Session["Notificaciones"] = listaNotificaciones;
                        }
                        FormsAuthentication.SetAuthCookie(oUsuario.Email, true);


                        Session["root"] = Utilitarios.GetRoot();



                        Session["Usuario"] = oUsuario;
                        if (oUsuario.FK_Rol == 1)
                        {
                            return RedirectToAction("IndexAdmin", "Home");
                        }
                        else
                        {
                            return RedirectToAction("IndexUsuario", "Home");
                        }

                    }
                    else
                    {
                        ViewData["Mensaje"] = "Usuario no encontrado";
                        return View();
                    }
            }
                else
            {
                ViewData["Mensaje"] = "Algún dato no coincide o no fue digitado.";
                return View();
            }
        }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;

                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }


        }

        public ActionResult UnAuthorized()
        {
            ViewBag.Message = "No autorizado";
            if (Session["User"] != null)
            {
                Usuario usuario = Session["User"] as Usuario;
                Log.Warn($"No autorizado {usuario.Email}");
            }
            return View();
        }

    }
}

Web/Views/Autentificacion/Login.cshtml
@model Infraestructure.Models.Usuario

@{
    Layout = null;
}

<!DOCTYPE html>

<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Login - MiCondominio</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/css/themify-icons.css" rel="stylesheet" />
    <link href="~/Content/css/metisMenu.css" rel="stylesheet" />
    <link href="~/Content/css/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/Content/css/slicknav.min.css" rel="stylesheet" />

    <!-- amchart css -->
    <link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />
    <!-- others css -->
    <link href="~/Content/css/typography.css" rel="stylesheet" />
    <link href="~/Content/css/default-css.css" rel="stylesheet" />
    <link href="~/Content/css/styles.css" rel="stylesheet" />
    <link href="~/Content/css/responsive.css" rel="stylesheet" />
    <!-- modernizr css -->
    <script src="~/Scripts/js/vendor/modernizr-2.8.3.min.js"></script>

</head>

<body>
    <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <!-- preloader area start -->
    <div id="preloader">
        <div class="loader"></div>
    </div>
    <!-- preloader area end -->
    <!-- login area start -->
    <div class="login-area login-s2">
        <div class="container">
            <div class="login-box ptb--100">
                @using (Html.BeginForm("Login", "Autentificacion", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="login-form-head">
                        <h4>Inicio de Sesión</h4>
                        <p>Descubre todas las comodidades y servicios que ofrecemos en nuestro condomio</p>
                    </div>
                    <div class="login-form-body">
                        <div class="form-gp">
                            @Html.LabelFor(model => model.Email, htmlAttributes: new { @for = "exampleInputEmail1" })
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @name = "email", @id = "exampleInputEmail1" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                            <i class="ti-email"></i>
                            <div class="text-danger"></div>
                        </div>
                        <div class="form-gp">
                            @Html.LabelFor(model => model.Clave, htmlAttributes: new { @for = "exampleInputPassword1" })
                            @Html.EditorFor(model => model.Clave, new { htmlAttributes = new { @name = "clave", type = "password", @id = "exampleInputPassword1" } })
                            @Html.ValidationMessageFor(model => model.Clave, "", new { @class = "text-danger" })
                            <i class="ti-lock"></i>
                            <div class="text-danger"></div>
                        </div>
                        <div class="row mb-4 rmber-area">
                            <div class="col-12 text-right">
                                <a href="@Url.Action("RecuperarContrasenna","Autentificacion")">Olvidó la contraseña?</a>
                            </div>
                        </div>
                        <div class="submit-btn-area">
                            <button id="form_submit" type="submit">Ingresar <i class="ti-arrow-right"></i></button>
                        </div>
                        <div class="form-footer text-center mt-5">
                            <p class="text-danger">@ViewData["Mensaje"]</p>
                        </div>
                    </div>

                }
            </div>
        </div>
    </div>
    <!-- login area end -->
    <!-- bootstrap 4 js -->
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/js/popper.min.js"></script>
    <script src="~/Scripts/js/bootstrap.min.js"></script>
    <script src="~/Scripts/js/owl.carousel.min.js"></script>
    <script src="~/Scripts/js/metisMenu.min.js"></script>
    <script src="~/Scripts/js/jquery.slimscroll.min.js"></script>
    <script src="~/Scripts/js/jquery.slicknav.min.js"></script>

    <!-- others plugins -->
    <script src="~/Scripts/js/plugins.js"></script>
    <script src="~/Scripts/js/scripts.js"></script>

</body>

</html>

Web/Views/Autentificacion/RecuperarContrasenna.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    @Scripts.Render("~/bundles/jquery")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/jqueryUI")
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <meta name="viewport" content="width=device-width" />
    <title>RecuperarContrasenna</title>
</head>
<body>


    <div class="error-area ptb--100 text-center">
        <div class="container">
            <div class="error-content">

                <div class="mb-5 p-4 bg-white shadow-sm">
                    <div id="stepper3" class="bs-stepper">
                        <div class="bs-stepper-header" role="tablist">
                            <div class="step" data-target="#test-nlf-1">
                                <button type="button" class="step-trigger" role="tab" id="stepper3trigger1" aria-controls="test-nlf-1" aria-selected="false">
                                    <span class="bs-stepper-circle bg-siteColor">
                                        <span class="fa-solid fa-envelope" aria-hidden="true"></span>
                                    </span>
                                    <span class="bs-stepper-label">Email</span>
                                </button>
                            </div>
                            <div class="bs-stepper-line"></div>
                            <div class="step active" data-target="#test-nlf-2">
                                <button type="button" class="step-trigger" role="tab" id="stepper3trigger2" aria-controls="test-nlf-2" aria-selected="true">
                                    <span class="bs-stepper-circle bg-siteColor">
                                        <span class="fa-solid fa-key" aria-hidden="true"></span>
                                    </span>
                                    <span class="bs-stepper-label">Código único</span>
                                </button>
                            </div>
                            <div class="bs-stepper-line"></div>
                            <div class="step" data-target="#test-nlf-3">
                                <button type="button" class="step-trigger" role="tab" id="stepper3trigger3" aria-controls="test-nlf-3" aria-selected="false">
                                    <span class="bs-stepper-circle bg-siteColor">
                                        <span class="fa-solid fa-lock" aria-hidden="true"></span>
                                    </span>
                                    <span class="bs-stepper-label">Restablecer</span>
                                </button>
                            </div>
                        </div>
                        <div class="bs-stepper-content">
                            <form onsubmit="return false">
                                <div id="test-nlf-1" role="tabpanel" class="bs-stepper-pane fade dstepper-block dstepper-none" aria-labelledby="stepper3trigger1">

                                    <p class="lead">
                                        Digite el correo asociado a su cuenta
                                    </p>
                                    <div class="form-group">

                                        <input id="txtEmail" name="txtEmail" class="inputname form-control" type="email" />
                                        <span id="txtEmailValidation" class="text-danger validation"> </span>
                                    </div>
                                    <div class="invoice-buttons text-right">
                                        <button class="btn bg-siteColor text-white" id="btnEnviarEmail">Siguiente</button>
                                    </div>
                                </div>

                                <div id="test-nlf-2" role="tabpanel" class="bs-stepper-pane fade dstepper-block active" aria-labelledby="stepper3trigger2">
                                    <p class="lead">
                                        Digite el código de verificación enviado a su email.
                                    </p>
                                    <div class="form-group">
                                        <input id="txtCodigo" class="inputname form-control" type="text" placeholder="" />
                                        <span id="txtCodigoValidation" class="text-danger validation"> </span>
                                    </div>

                                    <div class="invoice-buttons text-right">
                                        <button id="btnVerificarCodigo" class="btn bg-siteColor text-white">Siguiente</button>
                                    </div>
                                </div>
                                <div id="test-nlf-3" role="tabpanel" class="bs-stepper-pane fade text-center dstepper-block dstepper-none" aria-labelledby="stepper3trigger3">

                                    <p class="lead">
                                        Digite su nueva contraseña.
                                    </p>
                                    <div class="form-group">
                                        <input id="txtClave" class="inputname form-control" type="text" placeholder="" />
                                        <span id="txtClaveValidation" class="text-danger validation"> </span>
                                    </div>

                                    <div class="invoice-buttons text-right">
                                        <button id="btnCambiarContra" class="btn bg-siteColor text-white">Confirmar Cambio</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>




    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/complementos")
    @Scripts.Render("~/bundles/jqueryUI")

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        var stepper3;
        $(document).ready(function () {
            $('.validation').text('');

            const Toast = Swal.mixin({
                toast: true,
                position: 'top-end',
                showConfirmButton: false,
                timer: 3000,
                timerProgressBar: true,
                didOpen: (toast) => {
                    toast.addEventListener('mouseenter', Swal.stopTimer)
                    toast.addEventListener('mouseleave', Swal.resumeTimer)
                }
            })


            stepper3 = new Stepper(document.querySelector('#stepper3'), {
                linear: true,
                animation: true
            });




            $("#btnEnviarEmail").on("click", function () {
                $('.validation').text('');
                var email = $("#txtEmail").val();

                if (!validarCorreo(email)) {
                    $('#txtEmailValidation').text("Formato Incorrecto");
                    return;
                }

                $.ajax({
                    url: '@Url.Action("RestablecerContrasenna", "Autentificacion")',
                    data: {
                        email:email,
                    },
                    type: "POST",
                    success: function (response) {
                        $.LoadingOverlay("hide");
                        if (response) {
                            stepper3.next();
                        } else {
                            Toast.fire({
                                icon: 'error',
                                title: 'Error al consultar'
                            })
                        }
                    },
                    beforeSend: function () {
                        //Muestra el loading
                        $.LoadingOverlay("show", {
                            image: "",
                            fontawesome: "fa fa-cog fa-spin",
                        });
                    },
                });


            });


            $("#btnVerificarCodigo").on("click", function () {
                var codigo = $("#txtCodigo").val();

                $.ajax({
                    url: '@Url.Action("VerificarCodRestablecer", "Autentificacion")',
                    data: {
                        codigo : codigo,
                    },
                    type: "POST",
                    success: function (response)
                    {
                        $.LoadingOverlay("hide");
                        if (response) {
                            stepper3.next();
                        } else {
                            Toast.fire({
                                icon: 'error',
                                title: 'El código no coincide'
                            })
                        }
                    },
                    beforeSend: function () {
                        //Muestra el loading
                        $.LoadingOverlay("show", {
                            image: "",
                            fontawesome: "fa fa-cog fa-spin",
                        });
                    },
                });


            });

            $("#btnCambiarContra").on("click", function () {
                var clave = $("#txtClave").val();

                $.ajax({
                    url: '@Url.Action("CambiarClave", "Autentificacion")',
                    data: {
                        clave : clave,
                    },
                    type: "POST",
                    success: function (response)
                    {
                        $.LoadingOverlay("hide");
                        if (response) {
                                Swal.fire({
                                    title: 'Contraseña restablecida ',
                                    text: 'Se restableció su contraseña',
                                    icon: 'success',
                                    confirmButtonColor: '#5eb548',
                                    confirmButtonText: 'Iniciar Sesión',

                                }).then((result) => {
                                    window.location.href = "@Url.Action("Login", "Autentificacion")";
                                })
                        } else {
                            Toast.fire({
                                icon: 'error',
                                title: 'Error al cambiar la contraseña'
                            })
                        }
                    },
                    beforeSend: function () {
                        //Muestra el loading
                        $.LoadingOverlay("show", {
                            image: "",
                            fontawesome: "fa fa-cog fa-spin",
                        });
                    },
                });


            });


     function validarCorreo(correo) {
      var expresionRegular = @Html.Raw("/\\S+@\\S+\\.\\S+/");
      return expresionRegular.test(correo);
     }

        });

    </script>
</body>
</html>

Web/Views/Autentificacion/UnAuthorized.cshtml
@{
    ViewBag.Title = "Usuario no autorizado";
    Infraestructure.Models.Usuario usuario = Session["Usuario"] as Infraestructure.Models.Usuario;
    Layout = null;
}

@Scripts.Render("~/bundles/jquery")
@Styles.Render("~/Content/css")
@Styles.Render("~/Content/jqueryUI")
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>

@*<div id="preloader">
        <div class="loader"></div>
    </div>*@
<!-- preloader area end -->
<!-- error area start -->
<div class="error-area ptb--100 text-center">
    <div class="container">
        <div class="error-content">
            <h2>No Autorizado</h2>
            <p>¡No tiene los permisos necesarios para acceder a esta página!</p>
            @if (usuario == null)
            {
                @Html.ActionLink("Regresar", "Login", "Autentificacion", null, new { @class = "btn btn-primary btn-lg", @style = "margin-right:10px;" })
            }
            else if (usuario.FK_Rol == 1)
            {
                @Html.ActionLink("Regresar", "IndexAdmin", "Home", null, new { @class = "btn btn-primary btn-lg", @style = "margin-right:10px;" })
            }
            else if (usuario.FK_Rol == 2)
            {
                @Html.ActionLink("Regresar", "IndexUsuario", "Home", null, new { @class = "btn btn-primary btn-lg", @style = "margin-right:10px;" })
            }

        </div>
    </div>
</div>

@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/complementos")
@Scripts.Render("~/bundles/jqueryUI")
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>