Web/Controllers/ArchivoController.cs
using ApplicationCore.Services;
using Infraestructure.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class ArchivoController : Controller
    {
        private readonly IServiceArchivo _Service;

        public ArchivoController() => _Service = new ServiceArchivo();

        // GET: Archivo
        public ActionResult Index()
        {
            IEnumerable<Archivo> lista = _Service.GetAll();
            return View(lista);
        }

        [HttpPost]
        public ActionResult CargarPDF(HttpPostedFileBase archivo)
        { 
            if (archivo != null && archivo.ContentLength > 0)
            {
                //Leer archivo PDF desde el stream y guardarlo en una variable
                var archivoPDF = new byte[archivo.ContentLength];
                archivo.InputStream.Read(archivoPDF, 0, archivo.ContentLength);

                //Crear nueva entidad ArchivoPDF y asignar el archivo al contenido PDF
                Archivo nuevoArchivo = new Archivo { Nombre=archivo.FileName,Contenido = archivoPDF };
                _Service.Save(nuevoArchivo);

            }

            return RedirectToAction("Index");
        }

        public ActionResult DescargarPDF(int id)
        {
            //Seleccionar la entidad ArchivoPDF correspondiente al ID de la solicitud
            Archivo oArchivo = _Service.Get(id);

            if (oArchivo == null)
            {
                return HttpNotFound();
            }

            //Devolver el archivo PDF como un archivo para descargar
            return File(oArchivo.Contenido, "application/pdf", $"{oArchivo.Nombre}.pdf");
        }
    }
}

Web/Controllers/EstadoCuentaController.cs
using Antlr.Runtime.Misc;
using ApplicationCore.Services;
using Infraestructure.Models;
using Infraestructure.Repository;
using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using Web.Permisos;
using Web.Utils;


namespace Web.Controllers
{
    //[Authorize]
    public class EstadoCuentaController : Controller
    {
        private readonly IServiceEstadoCuenta _Service;

        public EstadoCuentaController() => _Service = new ServiceEstadoCuenta();

        [CustomAuthorize((int)Roles.Admin)]

        // GET: EstadoCuenta/Details/5
        public ActionResult Index(int? id, bool? active)
        {

            try
            {
                IEnumerable<Factura> lista = null;

                if (active.HasValue)
                {
                    lista = _Service.GetEstadoCuentaByFilter((bool)active, (int)id);
                }
                else
                {
                    lista = _Service.GetByIdProp((int)id);
                }

                return View(lista);
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;

                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        
    }

        [CustomAuthorize((int)Roles.Admin)]
        public ActionResult EstadosCuentaPendientes()
        {
            IEnumerable<Factura> lista = null;
            try
            {
                lista = _Service.GetEstadoCuentaPendiente();
                return View(lista);
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos!" + ex.Message;
                return RedirectToAction("Default", "Error");
            }


        }
        [CustomAuthorize((int)Roles.Admin)]
        public ActionResult DetalleEstadoCuenta(int idEstadoCuenta)
        {
            Factura oFactura = null;
            try
            {
                oFactura = _Service.GetDetalleEstadoCuenta(idEstadoCuenta);
                return View(oFactura);
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos!" + ex.Message;
                return RedirectToAction("Default", "Error");
            }
        }
        [CustomAuthorize((int)Roles.Admin)]
        // GET: EstadoCuenta/Create
        public ActionResult Create()
        {
            ViewBag.idPropiedad = listaPropiedades();
            ViewBag.idPlanCobro = listaPlanCobro();
            ViewBag.listaFacturasXMes = _Service.GetFacturasByFecha();
            return View();
    }


        // GET: EstadoCuenta/Edit/5
        public ActionResult Edit(int id) => View();

        // POST: EstadoCuenta/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Factura factura)
        {
            try
            {
                IServiceEstadoCuenta _ServiceEstadoCuenta = new ServiceEstadoCuenta();
                try
                {
                    IServiceNotificacionUsuario _ServiceNotificaion = new ServiceNotificacionUsuario();
                    IServicePropiedad _ServicePropiedad = new ServicePropiedad();
                    ModelState.Remove("FechaFacturacion");
                    ModelState.Remove("Tarjeta");
                    ModelState.Remove("Activo");

                    if (ModelState.IsValid)
                    {
                        factura.Activo = true;
                        factura.FK_Tarjeta = 1;
                        factura.FechaFacturacion = DateTime.Now;
                        factura.Tarjeta = "1234";

                        IEnumerable<Factura>  listaFacturas = _ServiceEstadoCuenta.GetByIdProp((int)factura.FK_Propiedad);
                        foreach (Factura oFact in listaFacturas)
                        {
                                if (oFact.FechaFacturacion.Value.Month == factura.FechaFacturacion.Value.Month && oFact.FechaFacturacion.Value.Year == factura.FechaFacturacion.Value.Year)
                                {
                                    ViewBag.idPropiedad = listaPropiedades(factura.FK_Propiedad);
                                    ViewBag.idPlanCobro = listaPlanCobro(factura.FK_PlanCobro);
                                    ViewBag.listaFacturasXMes = new ServiceEstadoCuenta().GetFacturasByFecha();
                                    TempData["existe"] = true;
                                    return View("Create", factura);
                                }                           
                        }

                        _ServiceEstadoCuenta.Create(factura);
                        _ServiceNotificaion.SaveNotificacionUsuario(new NotificacionUsuario { IdNotificacion = 5, IdUsuario = (int)_ServicePropiedad.GetPropiedadById((int)factura.FK_Propiedad).FK_Usuario, Leida = false });
                        ViewBag.idPropiedad = listaPropiedades();
                        ViewBag.idPlanCobro = listaPlanCobro();
                        TempData["creada"] = true;
                        return RedirectToAction("Create");

                    }
                    else
                    {
                        if (factura.Propiedad == null)
                        {
                            ViewBag.idPropiedad = listaPropiedades();
                        }
                        else
                        {
                            ViewBag.idPropiedad = listaPropiedades(factura.FK_Propiedad);
                        }

                        if (factura.PlanCobro == null)
                        {
                            ViewBag.idPlanCobro = listaPlanCobro();
                        }
                        else
                        {
                            ViewBag.idPlanCobro = listaPlanCobro(factura.FK_PlanCobro);
                        }
                        ViewBag.listaFacturasXMes = new ServiceEstadoCuenta().GetFacturasByFecha();
                        return View("Create", factura);                     
                    }
                }

                catch (Exception ex)
                {
                    // Salvar el error en un archivo 

                    TempData["Message"] = "Error al procesar los datos! " + ex.Message;
                    TempData["Redirect"] = "Home";
                    TempData["Redirect-Action"] = "IndexAdmin";
                    // Redireccion a la captura del Error
                    return RedirectToAction("Default", "Error");
                }
            }
            catch
            {
                return View();
            }
        }
        [HttpPost]
        public ActionResult UpdateNumTarjeta(int idFactura, string numTarjeta)
        {
            try
            {

                if (_Service.UpdateNumTarjeta(numTarjeta,idFactura) > 0)
                {
                    return Json(true, JsonRequestBehavior.AllowGet);
                }
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos!" + ex.Message;
                return RedirectToAction("Default", "Error");
            }
        }



        [HttpPost]
        public async Task<ActionResult> PagarFactura(int idFactura)
        {
            Factura oFactura = null;
            try
            {

                if (_Service.PagarFactura(idFactura) > 0)
                {
                    oFactura = _Service.GetDetalleEstadoCuenta(idFactura);
                    byte[] pdf = null;
                    if(oFactura != null)
                    {
                        pdf = _Service.GenerarPDF(oFactura);
                        if (pdf != null)
                        {
                            await _Service.EnviarPorCorreo(oFactura,pdf);
                            Session["factura"] = pdf;

                        }
                    }
                    return Json(true, JsonRequestBehavior.AllowGet);
                }
                return Json(false, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos!" + ex.Message;
                return RedirectToAction("Default", "Error");
            }
        }


        public ActionResult DescargarFactura()
        {

            try
            {
                return File(Session["factura"] as byte[], "application/pdf", "Factura.pdf");
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos!" + ex.Message;
                return RedirectToAction("Default", "Error");
            }
           
        }






        [CustomAuthorize((int) Roles.Residente)]
        public ActionResult PagarFactura()
        {
            Factura oFactura = null;
            Usuario oUsuario = null;
            try
            {
                oUsuario = Session["usuario"] as Usuario;
                IServiceEstadoCuenta _Service = new ServiceEstadoCuenta();
                oFactura = _Service.GetOldestFactura(oUsuario.Id);
                return View(oFactura);
            }
            catch (Exception ex)
            {

Web/Controllers/IncidenciaController.cs
using ApplicationCore.Services;
using Infraestructure.Models;
using Infraestructure.Repository;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using System.Web.Services.Description;
using Web.Permisos;
using Web.Utils;

namespace Web.Controllers
{
    public class IncidenciaController : Controller
    {
        private readonly IServiceIncidencias _Service;

        public IncidenciaController() => _Service = new ServiceIncidencias();


        [CustomAuthorize((int)Roles.Admin)]
        // GET: Incidencia
        public ActionResult IndexAdmin(int? EstadoIncidencia)
        {
            try
            {
                IEnumerable<Incidencias> lista = null;
                if (EstadoIncidencia != null)
                {
                    lista = _Service.GetByIdEstado((int)EstadoIncidencia);
                }
                else
                {
                    lista = _Service.GetAll();
                }

                ViewBag.listaEstadoIncidencia = listaEstadoIncidencia();

                return View(lista);
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;

                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }

        }
        [CustomAuthorize((int)Roles.Residente)]
        public ActionResult IndexUsuario()
        {
            try
            {

                Usuario usuario = (Usuario)Session["Usuario"];
                IEnumerable<Incidencias> lista = _Service.GetByIdUser(usuario.Id);
                ViewBag.listaIncidencias = lista;
                return View();
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;

                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }
        }


        [HttpPost]
        public void CambiarEstado(int id, string estado)
        {
            try
            {
                IEnumerable<Incidencias> lista = null;
                if (_Service.ActualizarEstadoIncidencia(id, int.Parse(estado)) >= 0)
                {
                    lista = _Service.GetAll();
                    ViewBag.listaEstadoIncidencia = listaEstadoIncidencia();
                    TempData["modificado"] = true;
                }
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;

                // Redireccion a la captura del Error
                RedirectToAction("Default", "Error");
            }

        }


        [ValidateAntiForgeryToken]
        public ActionResult CrearIncidencia(Incidencias oIncidencias)
        {
            Usuario usuario = (Usuario)Session["Usuario"];
            try
            {
                ModelState.Remove("FK_Usuario");
                ModelState.Remove("FK_Estado");
                ModelState.Remove("Fecha");
                if (ModelState.IsValid)
                {           

                        Incidencias oIncidencia = new Incidencias { Descripcion = oIncidencias.Descripcion, FK_Usuario = usuario.Id, Fecha = DateTime.Now, FK_Estado = 1 };
                        if (_Service.RegistrarIncidencia(oIncidencia) > 0)
                        {
                            IEnumerable<Incidencias> lista = _Service.GetByIdUser(usuario.Id);
                            ViewBag.listaIncidencias = lista;
                            TempData["creada"] = true;
                            return RedirectToAction("IndexUsuario");
                        }     
                }
                ViewBag.listaIncidencias = _Service.GetByIdUser(usuario.Id);
                return View("IndexUsuario");
            }
            catch (Exception ex)
            {
                Log.Error(ex, MethodBase.GetCurrentMethod());
                TempData["Message"] = "Error al procesar los datos! " + ex.Message;

                // Redireccion a la captura del Error
                return RedirectToAction("Default", "Error");
            }


        }

        private SelectList listaEstadoIncidencia(int? idEstado = 0)
        {

            IServiceEstados<EstadoIncidencia> _Service = new ServiceEstadoIncidencia();
            IEnumerable<EstadoIncidencia> lista = _Service.GetAll();
            return new SelectList(lista, "Id", "Nombre", idEstado);
        }




    }
}

Web/Views/Home/IndexAdmin.cshtml
@{ 
    var root = Session["root"];
}

<div class="col-lg-12">
    <div class="row">
        <div class="col-md-6 mt-5 mb-3">
            <div class="card  cardDashboard">
                <div class="seo-fact sbg1">
                    <div class="p-4 d-flex justify-content-between align-items-center">
                        <div class="seofct-icon"><i class="fa-solid fa-money-bill"></i>Ganancias</div>
                        <h2 id="totalGanancias"></h2>
                    </div>
                    <canvas id="seolinechart1" height="50"></canvas>
                </div>
            </div>
        </div>


        <div class="col-md-6 mt-5 mb-3">
            <a title="Mostrar Facturas Pendientes" href="@Url.Action("EstadosCuentaPendientes","EstadoCuenta")">
                <div class="card cardDashboard">
                    <div class="seo-fact sbg2">
                        <div class="p-4 d-flex justify-content-between align-items-center">
                            <div class="seofct-icon"><i class="fa-solid fa-warning"></i>Deudas</div>
                            <h2 id="cantDeudas"></h2>
                        </div>
                        <canvas id="seolinechart2" height="50"></canvas>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-md-6 mb-3 mb-lg-0">
            <a title="Mostrar Incidencias" href="@Url.Action("IndexAdmin","Incidencia")">
                <div class="card cardDashboard">
                    <div class="seo-fact sbg3">
                        <div class="p-4 d-flex justify-content-between align-items-center">
                            <div class="seofct-icon"><i class="fa-solid fa-warning"></i>Incidencias</div>
                            <h2 id="cantIncidencias"></h2>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-md-6 mb-3 mb-lg-0" data-toggle="modal" data-target="#modalReport">
            <a title="Mostrar Reportes">
                <div class="card cardDashboard">
                    <div class="seo-fact sbg4">
                        <div class="p-4 d-flex justify-content-between align-items-center">
                            <div class="seofct-icon"><i class="fa-solid fa-file"></i>Reportes</div>
                            <h2 id="cantIncidencias"></h2>
                        </div>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>


<div class="modal fade" id="modalReport">
    <div style="overflow-y: initial !important"
         class="modal-dialog modal-dialog-centered modal-lg modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" style="color: #000000; font-weight: bold;">Reportes</h5>
                <button type="button" class="close" data-dismiss="modal"><span>&times;</span></button>
            </div>
            <div class="modal-body" style="max-height: calc(100vh - 200px); overflow-y: auto;">

                <div class="card-body">
                    <nav>
                        <div class="nav nav-tabs" id="nav-tab" role="tablist">
                            <a class="nav-item nav-link active" id="nav-facturacion-tab" data-toggle="tab"
                               href="#nav-facturacion" role="tab" aria-controls="nav-facturacion"
                               aria-selected="false">Facturación</a>
                        </div>
                    </nav>
                    <div class="tab-content mt-3" id="nav-tabContent">
                        <div class="tab-pane fade show active" id="nav-contabilidad" role="tabpanel"
                             aria-labelledby="nav-contabilidad-tab">

                            <div class="row">
                                <!-- Buttons Items start -->
                                <div class="col-md-6 mt-5">
                                    <div class="list-group">

                                        <button type="button" class="btn btn-flat mb-3 mr-4 bg-dark text-white"
                                                id="btnReporteDeudas" data-toggle="modal"
                                                data-target="#modalDeudasP">
                                            <img src="~/Content/Images/pdf.png" /> Deudas Pendientes
                                        </button>

                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="tab-pane fade" id="nav-librosbancarios" role="tabpanel"
                             aria-labelledby="nav-librosbancarios-tab">
                            <button type="button" style="background-color: #444444; color: white;"
                                    class="btn btn-flat mb-3 mr-4" id="btnMSJReporteAsiento" data-toggle="modal"
                                    data-target="#modalMSJReporteAsiento">
                                <i style="font-size: 16px;" class="fa fa-print"></i> Reporte
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- <div class="modal-footer">

            </div> -->
        </div>
    </div>
</div>



<div class="modal fade" id="modalDeudasP">
    <div class="modal-dialog modal-dialog-centered modal-lg modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Deudas Pendientes</h5>
                <button type="button" class="close" data-dismiss="modal"><span>×</span></button>

            </div>
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>¡Aviso!</strong> Los campos que no digite, se omitirán en la consulta.
            </div>
            <div class="modal-body">
                <div class="row mb-1">
                    <div class="col-6">
                        <label for="FechaInicio">Fecha Inicio</label>
                        <input type="datetime" name="FechaInicio" id="FechaInicio" class="form-control" readonly="readonly" value="" data-histracont--histracont-target="dpFechaInicio">
                        <label class="control-label text-danger" id="validateFechaInicio" hidden="hidden"></label>
                    </div>

                    <div class="col-6">
                        <label for="FechaFin">Fecha Fin</label>
                        <input type="datetime" name="FechaFin" id="FechaFin" class="form-control" readonly="readonly" data-histracont--histracont-target="dpFechaFin">
                        <label class="control-label text-danger" id="validateFechaFin" hidden="hidden"></label>
                    </div>
                    <label for="selectPropiedad" class="control-label mx-5 mt-3">Número de propiedad</label>
                    <select class="form-control mx-5" aria-label="Default select example" id="selectPropiedad" name="selectPropiedad">
                        <option selected value="0">Seleccione una propiedad</option>
                        @foreach (var item in ViewBag.idPropiedad)
                        {
                            <option value="@item.Value">@item.Text</option>
                        }
                    </select>


                </div>
            </div>
            <div class="modal-footer">
                <div id="progressHISTRACONT" class="progress d-none mr-4 w-75">
                    <div class="progress-bar bg-success progress-bar-striped progress-bar-animated" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"></div>
                </div>
                <button id="generarReporte" class="btn btn-success" type="button">Generar Reporte</button>
                <button class="btn btn-flat bg-danger text-white" type="button" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>






@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $.ajax({
                url: '/Home/getHomeInfo',
                type: 'GET',
                success: function (response) {
                    lineChartGanancias(response.lista.map(item => item.Mes), response.lista.map(item => item.Total));
                    lineChartDeudas(response.listaDeudas.map(item => item.Mes), response.listaDeudas.map(item => item.Cantidad));
                    $("#totalGanancias").text("₡ " + response.totalGanancias);
                    $("#cantDeudas").text(response.cantDeudas);
                    $("#cantIncidencias").text(response.cantIncidencias);

                },
                error: function (error) {
                    // Manejar el error aquí
                }

            });
        });

        const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true,
            didOpen: (toast) => {
                toast.addEventListener('mouseenter', Swal.stopTimer)
                toast.addEventListener('mouseleave', Swal.resumeTimer)
            }
        })


        //Detecta cuanso abre el modal y le da el formato a los pickers
        $('#modalDeudasP').on('show.bs.modal', function () {
            setPicker();
        });


        //Setea el picker, si no viene nada pone la hora desde las 00:00 hasta las 23:59
        function setPicker() {

            $('#FechaInicio, #FechaFin').datetimepicker({
                format: 'd-m-Y H:i:s'
            });
            $.datetimepicker.setLocale('es'); //idioma español
        }

        function destroyPicker() {
            //$('#FechaInicio, #FechaFin').datetimepicker("destroy");  //destruir el picker
            $('#FechaInicio').val("");
            $('#FechaFin').val("");
        }

        //Verifica si la fecha de salida es mayor
        function isFechaFinMayor(fechaInicio, fechaFin) {
            if (fechaInicio >= fechaFin) {
                Toast.fire({
                    icon: 'error',
                    title: 'La hora de salida debe de ser mayor'
                });
                $('#FechaInicio').val("");
                $('#FechaFin').val("");
                return false;
            }
            return true;
        }

        $('#generarReporte').on("click", function () {
            //event.preventDefault();
            $("#validateFechaEntrada").addClass("d-none");
            $("#validateFechaSalida").addClass("d-none");
            $("#validateFechaSalida").text("");
            $("#validateFechaEntrada").text("");

            var fechaInicio = moment($('#FechaInicio').val(), 'DD-MM-YYYY HH:mm:ss').toDate(); //Transforma la fecha a date
            var fechaFin = moment($('#FechaFin').val(), 'DD-MM-YYYY HH:mm:ss').toDate();


            //Valida si el formato de fecha es valido o si viene vacio, en caso de que si ajusta la fecha al inicio del mes actual
            if (!moment($('#FechaInicio').val(), 'DD-MM-YYYY HH:mm:ss').isValid() || !$('#FechaInicio').val()) {
                fechaInicio = moment().startOf('month');
                fechaInicio = fechaInicio.toDate(); //Transforma la fecha a date
            }


            ////Valida si el formato de fecha es valido o si viene vacio, en caso de que si ajusta la fecha final del mes actual
            if (!moment($('#FechaFin').val(), 'DD-MM-YYYY HH:mm:ss').isValid() || !$('#FechaFin').val()) {
                fechaFin = moment().endOf('month');
                fechaFin = fechaFin.toDate(); //Transforma la fecha a date
            }

            // Obtener la referencia al elemento select
            var selectElement = document.getElementById("selectPropiedad");
            // Obtener la opción seleccionada
            var selectedOption = selectElement.options[selectElement.selectedIndex];
            var numPropiedad = selectedOption.text;
            if (selectedOption.text == "Seleccione una propiedad") {
                numPropiedad = null;
            }
            if (!isFechaFinMayor(fechaInicio, fechaFin)) {
                return;
            }

            $.ajax({
                url: "/Home/reporteDeudas",
                method: "POST",
                xhrFields: {
                    responseType: 'blob'
                },
                data: {
                    fechaFin: fechaFin.toISOString(),
                    fechaInicio: fechaInicio.toISOString(),
                    numPropiedad: numPropiedad,
                },
                success: function (response) {
                    if (response.size == 0) {
                        Toast.fire({
                            icon: 'error',
                            title: 'No hay facturas pendientes'
                        })
                        return;
                    } else {
                        var blob = new Blob([response], { type: 'application/pdf' });
                        var link = document.createElement('a');
                        link.href = window.URL.createObjectURL(blob);
                        link.download = 'Reporte de Deudas.pdf';
                        link.click();
                    }
                },
                error: function () {
                    console.log("ERROR")
                },
                complete: function () {
                    destroyPicker();
                },
            });


        });

    </script>




}

Web/Views/Home/IndexUsuario.cshtml
@{
    ViewBag.Title = "IndexUsuario";
    IEnumerable<Infraestructure.Models.Informacion> listaInformacion = ViewBag.listaInformacion;
    IEnumerable<Infraestructure.Models.Archivo> listaArchivos = ViewBag.listaArchivos;
}






<div class="row">

    <div class="col-md-9 col-12">
        @foreach (var item in listaInformacion)
        {
            <div class="card mt-3">
                <div class="card-header">
                    @item.Titulo
                </div>
                <div class="card-body">
                    <p class="card-text">@item.Descripcion</p>
                </div>
            </div>
        }
    </div>




    <div class="col-md-3 col-12">
        <div class="">
            <div class="card">
                <div class="card-body">
                    <h4 class="header-title">Archivos Documentales</h4>
                    <ul class="list-group">
                        @foreach (var item in listaArchivos)
                        {
                            <li class="list-group-item"><a class="text-siteColor" href="@Url.Action("DescargarPDF", "Archivo", new { id = item.Id })">@item.Nombre</a></li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>